spring:
  application:
    name: demo-livraria

#---- Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    display-request-duration: true
  openapi:
    title: 'API de Gerenciamento de Autores'
    description: 'API RESTful para gerenciamento de dados de autores'
    version: '1.0.0'