spring:
  application:
    name: demo-livraria

#---- Banco de dados MySQL
  jpa:
    hibernate:
      ddl-auto: update  # Can be 'create', 'update', 'create-drop', 'validate' (use 'none' in production)
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/demo_livraria_db?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

#---- Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    display-request-duration: true
  openapi:
    title: 'API de Gerenciamento de Livros'
    description: 'API RESTful para gerenciamento de dados de livros e seus autores e generos'
    version: '1.0.0'