spring:
  application:
    name: demo-livraria

#---- Banco de dados em memoria H2
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database, or use "jdbc:h2:file:./data/testdb" for file-based
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update  # Can be 'create', 'update', 'create-drop', 'validate' (use 'none' in production)
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


#---- Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    display-request-duration: true
  openapi:
    title: 'API de Gerenciamento de Autores'
    description: 'API RESTful para gerenciamento de dados de autores'
    version: '1.0.0'